### ISSUE TITLE
創世神女 ‧ 女媧不是增回

### ISSUE THREAD

**Issue by ifqblerr** [tinghan33704/tos_skill_filter#2]
https://tinghan33704.github.io/tos_skill_filter/tos_skill_filter.html?search=00000000000001000000000&attr=0&race=00&star=00&chrg=0&or=1

**Comment by tinghan33704** [comment]
因為增加 Ex.Combo 目前沒有獨立出一類
而攻擊力和回復力是會隨 Ex.Combo 增加而提升
因此目前先分在這兩類

如果日後有新增增加 Ex.Combo 這一功能的話
會考慮將她和西王母從增攻、增回類移除
